cacheFolder: ./.yarn/cache

compressionLevel: 0

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableImmutableInstalls: false

enableProgressBars: true

enableScripts: true

httpRetry: 3

httpTimeout: 30000

networkConcurrency: 50

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
